# Generated by Django 2.2.3 on 2019-12-24 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goodsID', models.IntegerField(default=200000, primary_key=True, serialize=False, verbose_name='货物编号:')),
                ('goods_name', models.CharField(default='请输入货物名称', max_length=20, verbose_name='货物名称:')),
                ('goods_price', models.FloatField(default=0, verbose_name='货物成本:')),
                ('goods_sprice', models.FloatField(default=0, verbose_name='货物售价:')),
                ('goods_discount', models.FloatField(default=0.0, verbose_name='折扣:')),
                ('goods_amount', models.IntegerField(default=0, verbose_name='在售数量:')),
                ('update_date', models.DateTimeField(null=True, verbose_name='更新日期:')),
            ],
            options={
                'verbose_name': '商品信息管理',
                'verbose_name_plural': '商品信息管理',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supID', models.IntegerField(null=True, verbose_name='供应商编号:')),
                ('sup_name', models.CharField(default='请输入供应商名称', max_length=20, verbose_name='供应商名称:')),
                ('sup_tel', models.IntegerField(default=0, null=True, verbose_name='供应商电话:')),
            ],
            options={
                'verbose_name': '供应商管理',
                'verbose_name_plural': '供应商管理',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='姓名:')),
                ('sex', models.CharField(choices=[('female', '女'), ('male', '男')], default='女', max_length=10, verbose_name='性别:')),
                ('job', models.CharField(choices=[('用户', '用户'), ('仓库主管', '仓库主管'), ('普通员工', '普通员工')], default='普通员工', max_length=10, verbose_name='职位:')),
                ('job_num', models.IntegerField(verbose_name='工号:')),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL, verbose_name='用户名:')),
            ],
            options={
                'verbose_name': '员工信息管理',
                'verbose_name_plural': '员工信息管理',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('goods_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='storage', serialize=False, to='app.Goods', verbose_name='货物名称:')),
                ('storage_amount', models.IntegerField(default=0, null=True, verbose_name='现有库存:')),
                ('storage_max', models.IntegerField(default=1000, null=True, verbose_name='最大库存量:')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='更新日期:')),
            ],
            options={
                'verbose_name': '商品库存管理',
                'verbose_name_plural': '商品库存管理',
            },
        ),
        migrations.CreateModel(
            name='WaveHousing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入库时间')),
                ('in_price', models.FloatField(verbose_name='入库单价:')),
                ('in_amount', models.IntegerField(verbose_name='入库数量:')),
                ('in_ps', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注:')),
                ('pay_status', models.BooleanField(default=False)),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Goods', verbose_name='货物名称:')),
                ('res_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo', verbose_name='经办人姓名:')),
                ('sup_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Supplier', verbose_name='供应商名称:')),
            ],
            options={
                'verbose_name': '入库单管理',
                'verbose_name_plural': '入库单管理',
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_date', models.DateTimeField(verbose_name='出库时间:')),
                ('out_amount', models.IntegerField(verbose_name='出库数量:')),
                ('out_ps', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注:')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Goods', verbose_name='货物名称:')),
                ('res_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo', verbose_name='经办人姓名:')),
                ('sup_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Supplier', verbose_name='供应商名称:')),
            ],
            options={
                'verbose_name': '出库单管理',
                'verbose_name_plural': '出库单管理',
            },
        ),
        migrations.CreateModel(
            name='SellOut',
            fields=[
                ('ssid', models.IntegerField(primary_key=True, serialize=False, verbose_name='销售编号')),
                ('out_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='销售时间:')),
                ('out_amount', models.IntegerField(default=1, verbose_name='销售数量:')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_goods', to='app.Goods', verbose_name='货物名称:')),
                ('res_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo', verbose_name='用户姓名:')),
            ],
            options={
                'verbose_name': '销售管理',
                'verbose_name_plural': '销售管理',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_sup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Supplier', verbose_name='供应商名称'),
        ),
    ]
